stages:
  create_dirs:
    cmd: mkdir -p -v data/ output/ model_output/
  install:
    cmd: pip install -r requirements.txt
    deps:
      - requirements.txt
  activate_venv:
    cmd: source .venv/bin/activate
  import_data:
    cmd: ./import_data.sh
    deps:
      - data/
      - output/
      - model_output/
  clean_data:
    cmd: clean_data.py --input "data/raw/insurance.csv" --output "data/transform/insurance_000.parquet"
    deps:
      - data/
  eda:
    cmd: python eda.py --input data/transform/insurance_000.parquet --output output/eda_combined_plots.png
    deps:
      - clean_data
  split_data:
    cmd: python split_data.py --data data/transform/insurance_000.parquet --strategy train_test_split --test_size 0.2
    deps:
      - eda
  evaluate_model:
    cmd: python evaluate.py --criterion squared_error --min_samples_leaf 10 --max_leaf_nodes 5 --degree 3
    deps:
      - split_data